#!/bin/bash
		
for (( i = 1; i <= 10; i++ )); do
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	sleep 2
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	sleep 2
done
