#!/bin/bash
		
for (( i = 1; i <= 30; i++ )); do
	sleep 2
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 1
	sleep 2
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 4
	sleep 0.5
	adb shell am broadcast -a com.living.subdisplayservice.demo.keyevent --ei keycode 12
done
