#!/bin/bash

function_print_usage(){
	echo "*****************************************************************"
	echo "*                      gopath ver0.01                           *"
	echo "*****************************************************************"
	echo "func :                         "
	echo "add [alias] [absPATH] : save 'alias' as a shortcut to absPATH         "
	echo "del [alias] : remove a saved 'alias' as a shortcut to absPATH         "
	echo "-----------------------------------------------------------------"
	#token_W
	echo "alias :  run \"gop [alias]\" to skip to dir                      "
	echo "W: ${workroot} "
	#token_A3
	echo "A3: ${ase3_dir}      "
	#token_A
	echo "A: ${apliroot}      "
	#token_b
	echo "b: ${shpathroot}      "
	#token_w
	echo "w: ${worker_dir}      "
	#token_as
	echo "as: ${asstartdir}      "
	#token_sh
	echo "sh: ${shell_dir}     "
	#token_py
	echo "py: ${python_dir}      "
	#token_fl
	echo "fl: ${flash_dir}       "
 	#token_aosp
	echo "aosp: ${aosp_dir}  "
 	#token_a2
	echo "a2: ${a2_dir}"
 	#token_mg
	echo "mg: ${mg_dir}"
 	#token_asp
	echo "asp: ${asp_dir}"
	#token_insert_usage
	echo "*****************************************************************"

}

function_add_usage(){
	echo "parse args to python script"
	fioc -f agop -a $1,$2
}

function_del_usage(){
	echo "parse args to python script"
	fioc -f dgop -a $1
}

shpathroot="/usr/local/bin"
amairoot="/home/amai"
workroot=${amairoot}/Work
ase3_dir=${workroot}/WM-motor/project/ASE-3
worker_dir=${workroot}/MY-github/work_tool/shell/MYPATHSHELL
apliroot=${amairoot}/Applications
asstartdir="/home/amai/Applications/1.AndroidStudio/android-studio/bin"
shell_dir=${workroot}/MY-github/work_tool/shell
python_dir=${workroot}/MY-github/work_tool/python
flash_dir=${ase3_dir}/releasedir/fastboot
aosp_dir=/home/amai/Work/AOSP
#token_a2
a2_dir=/home/amai/Work/WM-motor/project/ASE-2/gitdir
#token_mg
mg_dir=/home/amai/Work/MY-github/
#token_asp
asp_dir=/home/amai/AndroidStudioProjects
#token_insert_dir
 

if [[ $1 == "" ]]||[[ $1 == " " ]]||[[ $1 == "-h" ]]; then
	function_print_usage
elif [ $1 == "add" ]; then
	function_add_usage $2 $3
elif [ $1 == "del" ]; then
	function_del_usage $2
elif [ $1 == "W" ]; then
	echo "gopath $workroot"
	cd $workroot
elif [ $1 == "A3" ]; then
	echo "gopath $ase3_dir"
	cd $ase3_dir
elif [ $1 == "A" ]; then
	echo "gopath $apliroot"
	cd $apliroot
elif [ $1 == "b" ]; then
	echo "gopath $shpathroot"
	cd $shpathroot
elif [ $1 == "w" ]; then
	echo "gopath $worker_dir"
	cd $worker_dir
elif [ $1 == "as" ]; then
	echo "gopath $asstartdir"
	cd $asstartdir
elif [ $1 == "sh" ]; then
	echo "gopath $shell_dir"
	cd $shell_dir
elif [ $1 == "py" ]; then
	echo "gopath $python_dir"
	cd $python_dir
elif [ $1 == "fl" ]; then
	echo "gopath $flash_dir"
	cd $flash_dir
elif [ $1 == "aosp" ]; then
	echo "gopath /home/amai/Work/AOSP"
	cd ${aosp_dir}
#token_a2
elif [ $1 == "a2" ]; then
	echo "gopath /home/amai/Work/WM-motor/project/ASE-2/gitdir"
	cd ${a2_dir}
#token_mg
elif [ $1 == "mg" ]; then
	echo "gopath /home/amai/Work/MY-github/"
	cd ${mg_dir}
#token_asp
elif [ $1 == "asp" ]; then
	echo "gopath /home/amai/AndroidStudioProjects"
	cd ${asp_dir}
#token_insert_cmd
fi

